window.GAME_CONTENT = {
  species: [
    {
      id: "guppy",
      species: "Guppy",
      cost: 26,
      sellPrice: 14,
      rarity: "Commun",
      income: 6,
      growthHours: 120,
      colors: ["#ffd166", "#ff9d42"],
      sizeScale: 0.8,
      sprite: {
        file: "./assets/fish/Nouveaux/Guppy.png",
        w: 1536,
        h: 1024,
        tailSplit: 68,
        tailJoint: 62,
        displayHeight: 28,
        direction: -1,
      },
      biome: "Lagon",
      unlockLevel: 1,
      waterType: "fresh",
      temperatureMin: 22,
      temperatureMax: 26,
      oxygenMin: 45,
      oxygenPerCycle: 0.7,
      phMin: 6.8,
      phMax: 7.8,
      minSizeCm: 3,
      adultSizeCm: 6,
      speed: 78,
      reflex: 82,
      lifespanWeeks: 28,
      lifespanCycles: 28,
      preferredPlantId: "vallisneria-spiralis",
      behaviorProfile: {
        lane: "upper-mid",
        sociability: "shoaling",
        pace: "light",
        hoverChance: 0.14,
        inspectChance: 0.18,
        cruiseChance: 0.68,
      },
      description: "Petit poisson sociable et vif, ideal pour lancer un premier aquarium anime.",
    },
    {
      id: "betta-splendens",
      species: "Betta splendens",
      cost: 54,
      sellPrice: 28,
      rarity: "Rare",
      income: 11,
      growthHours: 156,
      colors: ["#7be0c0", "#45aaf2"],
      sizeScale: 1,
      sprite: {
        file: "./assets/fish/Nouveaux/Betta.png",
        w: 1536,
        h: 1024,
        tailSplit: 56,
        tailJoint: 50,
        displayHeight: 36,
        direction: -1,
      },
      biome: "Riziere calme",
      unlockLevel: 1,
      waterType: "fresh",
      temperatureMin: 25,
      temperatureMax: 29,
      oxygenMin: 54,
      oxygenPerCycle: 1.0,
      phMin: 6.2,
      phMax: 7.4,
      minSizeCm: 5,
      adultSizeCm: 7,
      speed: 65,
      reflex: 88,
      lifespanWeeks: 30,
      lifespanCycles: 30,
      preferredPlantId: "anubias-nana",
      behaviorProfile: {
        lane: "upper",
        sociability: "solitary",
        pace: "slow",
        hoverChance: 0.42,
        inspectChance: 0.22,
        cruiseChance: 0.36,
      },
      description: "Un solitaire elegant, plus contemplatif que rapide, mais tres reactif.",
    },
    {
      id: "neon-tetra",
      species: "Neon tetra",
      cost: 32,
      sellPrice: 18,
      rarity: "Peu commun",
      income: 8,
      growthHours: 108,
      colors: ["#4dd2ff", "#2a7cff"],
      sizeScale: 0.62,
      sprite: {
        file: "./assets/fish/Nouveaux/Tétra néon.png",
        w: 1536,
        h: 1024,
        tailSplit: 79,
        tailJoint: 73,
        displayHeight: 22,
        direction: -1,
      },
      biome: "Riviere claire",
      unlockLevel: 1,
      waterType: "fresh",
      temperatureMin: 22,
      temperatureMax: 26,
      oxygenMin: 40,
      oxygenPerCycle: 0.6,
      phMin: 6.0,
      phMax: 7.0,
      minSizeCm: 3,
      adultSizeCm: 4,
      speed: 85,
      reflex: 90,
      lifespanWeeks: 29,
      lifespanCycles: 29,
      preferredPlantId: "microsorum-java",
      behaviorProfile: {
        lane: "mid",
        sociability: "shoaling",
        pace: "swift",
        hoverChance: 0.1,
        inspectChance: 0.18,
        cruiseChance: 0.72,
      },
      description: "Un petit nageur de banc tres vif, parfait pour donner du rythme au milieu du bac.",
    },
    {
      id: "corydoras",
      species: "Corydoras",
      cost: 44,
      sellPrice: 24,
      rarity: "Peu commun",
      income: 10,
      growthHours: 168,
      colors: ["#f2b16d", "#da7a4d"],
      sizeScale: 0.86,
      sprite: {
        file: "./assets/fish/Nouveaux/Corydoras.png",
        w: 1536,
        h: 1024,
        tailSplit: 74,
        tailJoint: 69,
        displayHeight: 30,
        direction: -1,
      },
      biome: "Fond de riviere",
      unlockLevel: 1,
      waterType: "fresh",
      temperatureMin: 22,
      temperatureMax: 27,
      oxygenMin: 66,
      oxygenPerCycle: 1.4,
      phMin: 6.4,
      phMax: 7.4,
      minSizeCm: 5,
      adultSizeCm: 7,
      speed: 40,
      reflex: 60,
      lifespanWeeks: 36,
      lifespanCycles: 36,
      preferredPlantId: "anubias-nana",
      behaviorProfile: {
        lane: "bottom",
        sociability: "shoaling",
        pace: "slow",
        hoverChance: 0.34,
        inspectChance: 0.38,
        cruiseChance: 0.28,
      },
      description: "Poisson de fond robuste et paisible, utile pour apporter de la vie en zone basse.",
    },
    {
      id: "gourami-perle",
      species: "Gourami perle",
      cost: 86,
      sellPrice: 46,
      rarity: "Rare",
      income: 14,
      growthHours: 228,
      colors: ["#d8d0ff", "#91f0e8"],
      sizeScale: 1.16,
      sprite: {
        file: "./assets/fish/Nouveaux/Gourami perle.png",
        w: 1536,
        h: 1024,
        tailSplit: 72,
        tailJoint: 68,
        displayHeight: 42,
        direction: -1,
      },
      biome: "Eaux calmes",
      unlockLevel: 1,
      waterType: "fresh",
      temperatureMin: 24,
      temperatureMax: 28,
      oxygenMin: 58,
      oxygenPerCycle: 1.1,
      phMin: 6.4,
      phMax: 7.4,
      minSizeCm: 10,
      adultSizeCm: 12,
      speed: 55,
      reflex: 70,
      lifespanWeeks: 34,
      lifespanCycles: 34,
      preferredPlantId: "echinodorus-bleheri",
      behaviorProfile: {
        lane: "upper-mid",
        sociability: "paired",
        pace: "balanced",
        hoverChance: 0.28,
        inspectChance: 0.24,
        cruiseChance: 0.48,
      },
      description: "Un poisson plus impose et pose, ideal pour donner du volume au bac principal.",
    },
    {
      id: "platy",
      species: "Platy",
      cost: 36,
      sellPrice: 20,
      rarity: "Commun",
      income: 7,
      growthHours: 144,
      colors: ["#ffad7a", "#ffd166"],
      sizeScale: 0.84,
      sprite: {
        file: "./assets/fish/Nouveaux/Platy.png",
        w: 1536,
        h: 1024,
        tailSplit: 72,
        tailJoint: 67,
        displayHeight: 31,
        direction: -1,
      },
      biome: "Lagon plante",
      unlockLevel: 1,
      waterType: "fresh",
      temperatureMin: 22,
      temperatureMax: 26,
      oxygenMin: 50,
      oxygenPerCycle: 0.9,
      phMin: 7.0,
      phMax: 8.0,
      minSizeCm: 4,
      adultSizeCm: 7,
      speed: 72,
      reflex: 75,
      lifespanWeeks: 32,
      lifespanCycles: 32,
      preferredPlantId: "cryptocoryne-wendtii",
      behaviorProfile: {
        lane: "mid",
        sociability: "grouped",
        pace: "balanced",
        hoverChance: 0.16,
        inspectChance: 0.24,
        cruiseChance: 0.6,
      },
      description: "Un poisson accessible, colore et stable, parfait pour densifier un aquarium jeune.",
    },
    {
      id: "danio-rerio",
      species: "Danio rerio",
      cost: 42,
      sellPrice: 22,
      rarity: "Peu commun",
      income: 8,
      growthHours: 132,
      colors: ["#9edbff", "#4aa4ff"],
      sizeScale: 0.68,
      sprite: {
        file: "./assets/fish/Nouveaux/Danio rerio.png",
        w: 1536,
        h: 1024,
        tailSplit: 77,
        tailJoint: 72,
        displayHeight: 24,
        direction: -1,
      },
      biome: "Riviere vive",
      unlockLevel: 1,
      waterType: "fresh",
      temperatureMin: 20,
      temperatureMax: 25,
      oxygenMin: 40,
      oxygenPerCycle: 0.6,
      phMin: 6.5,
      phMax: 7.5,
      minSizeCm: 4,
      adultSizeCm: 5,
      speed: 95,
      reflex: 95,
      lifespanWeeks: 27,
      lifespanCycles: 27,
      preferredPlantId: "microsorum-java",
      behaviorProfile: {
        lane: "upper-mid",
        sociability: "shoaling",
        pace: "swift",
        hoverChance: 0.08,
        inspectChance: 0.16,
        cruiseChance: 0.76,
      },
      description: "Un petit sprinteur de surface, tres nerveux et tres mobile dans le bac.",
    },
  ],
  plants: [
    {
      id: "anubias-nana",
      species: "Anubias nana",
      rarity: "Commun",
      biome: "Sous-bois calme",
      unlockLevel: 1,
      temperatureMin: 22,
      temperatureMax: 28,
      oxygenGeneration: 0.4,
      comfortBonus: 5,
      phMin: 6.0,
      phMax: 7.6,
      lightMin: 6,
      lightMax: 10,
      co2Need: 0.3,
      minSizeCm: 5,
      maxSizeCm: 15,
      lifespanCycles: 36,
      fryProtection: 8,
      contestPresence: 8,
      sizeScale: 1,
      sprite: {
        file: "./assets/plants/Nouveaux/Anubias nana.png",
        w: 768,
        h: 768,
        displayHeight: 44,
        rootCut: 17,
        swayAngle: 2.4,
        swayDuration: 7.6,
      },
      description: "Une plante compacte et stable, parfaite pour lancer un aquarium plante sans prise de risque.",
    },
    {
      id: "microsorum-java",
      species: "Microsorum (fougere de Java)",
      rarity: "Peu commun",
      biome: "Roche ombragee",
      unlockLevel: 1,
      temperatureMin: 22,
      temperatureMax: 28,
      oxygenGeneration: 0.5,
      comfortBonus: 6,
      phMin: 6.0,
      phMax: 7.5,
      lightMin: 6,
      lightMax: 10,
      co2Need: 0.4,
      minSizeCm: 10,
      maxSizeCm: 30,
      lifespanCycles: 35,
      fryProtection: 12,
      contestPresence: 10,
      sizeScale: 1,
      sprite: {
        file: "./assets/plants/Nouveaux/Fougere-de-Java.png",
        w: 768,
        h: 768,
        displayHeight: 72,
        rootCut: 16,
        swayAngle: 3.4,
        swayDuration: 6.8,
      },
      description: "Une fougere souple et elegante qui apporte du volume sans trop exiger de CO2.",
    },
    {
      id: "cryptocoryne-wendtii",
      species: "Cryptocoryne wendtii",
      rarity: "Peu commun",
      biome: "Berge tropicale",
      unlockLevel: 1,
      temperatureMin: 22,
      temperatureMax: 28,
      oxygenGeneration: 0.6,
      comfortBonus: 6,
      phMin: 6.2,
      phMax: 7.4,
      lightMin: 7,
      lightMax: 11,
      co2Need: 0.5,
      minSizeCm: 8,
      maxSizeCm: 20,
      lifespanCycles: 34,
      fryProtection: 10,
      contestPresence: 9,
      sizeScale: 1,
      sprite: {
        file: "./assets/plants/Nouveaux/Cryptocoryne wendtii.png",
        w: 768,
        h: 768,
        displayHeight: 56,
        rootCut: 18,
        swayAngle: 2.8,
        swayDuration: 7.1,
      },
      description: "Une plante dense et chaude, ideale pour meubler le milieu du bac avec douceur.",
    },
    {
      id: "vallisneria-spiralis",
      species: "Vallisneria spiralis",
      rarity: "Rare",
      biome: "Herbier haut",
      unlockLevel: 1,
      temperatureMin: 20,
      temperatureMax: 28,
      oxygenGeneration: 0.9,
      comfortBonus: 4,
      phMin: 6.5,
      phMax: 8.0,
      lightMin: 8,
      lightMax: 12,
      co2Need: 0.7,
      minSizeCm: 20,
      maxSizeCm: 100,
      lifespanCycles: 38,
      fryProtection: 18,
      contestPresence: 7,
      sizeScale: 1,
      sprite: {
        file: "./assets/plants/Nouveaux/Vallisneria spiralis.png",
        w: 768,
        h: 768,
        displayHeight: 126,
        rootCut: 12,
        swayAngle: 6.2,
        swayDuration: 5.4,
      },
      description: "Une grande rubanee tres vivante qui donne de la hauteur et booste l'oxygene du bac.",
    },
    {
      id: "echinodorus-bleheri",
      species: "Echinodorus bleheri",
      rarity: "Rare",
      biome: "Fond luxuriant",
      unlockLevel: 1,
      temperatureMin: 22,
      temperatureMax: 30,
      oxygenGeneration: 1.0,
      comfortBonus: 7,
      phMin: 6.5,
      phMax: 7.8,
      lightMin: 8,
      lightMax: 12,
      co2Need: 0.8,
      minSizeCm: 20,
      maxSizeCm: 50,
      lifespanCycles: 37,
      fryProtection: 16,
      contestPresence: 12,
      sizeScale: 1,
      sprite: {
        file: "./assets/plants/Nouveaux/Echinodorus bleheri.png",
        w: 768,
        h: 768,
        displayHeight: 92,
        rootCut: 16,
        swayAngle: 3.2,
        swayDuration: 6.4,
      },
      description: "Une grande rosette ample qui structure le bac et offre un excellent rendement en oxygene.",
    },
  ],
  shopItems: [
    {
      id: "food-pack",
      name: "Granules marines",
      type: "food",
      amount: 6,
      cost: 28,
      tier: "Base",
      description: "Recharge 6 portions de nourriture premium.",
    },
    {
      id: "food-feast",
      name: "Banquet de plancton",
      type: "food",
      amount: 14,
      cost: 58,
      tier: "Confort",
      description: "Un stock plus rentable pour les aquariums qui grandissent.",
    },
    {
      id: "water-kit",
      name: "Kit de filtration",
      type: "water",
      amount: 20,
      cost: 36,
      tier: "Base",
      description: "Ajoute un kit de filtration pour un nettoyage renforce.",
    },
    {
      id: "water-premium",
      name: "Cycleur oceanique",
      type: "water",
      amount: 34,
      cost: 62,
      tier: "Premium",
      description: "Une maintenance haut de gamme pour les grands bacs.",
    },
    {
      id: "ph-up-tabs",
      name: "Pastilles pH+",
      type: "ph-up",
      amount: 4,
      cost: 32,
      tier: "Chimie",
      description: "Augmente legerement le pH du bac. Pack de 4 pastilles.",
    },
    {
      id: "ph-down-tabs",
      name: "Pastilles pH-",
      type: "ph-down",
      amount: 4,
      cost: 32,
      tier: "Chimie",
      description: "Baisse legerement le pH du bac. Pack de 4 pastilles.",
    },
    {
      id: "lamp-upgrade-2",
      name: "Lampe horticole II",
      type: "lamp",
      level: 2,
      cost: 74,
      tier: "Equipement",
      description: "Etend le reglage de luminosite jusqu'a 8 h d'exposition.",
    },
    {
      id: "lamp-upgrade-3",
      name: "Lampe horticole III",
      type: "lamp",
      level: 3,
      cost: 128,
      tier: "Equipement",
      description: "Etend le reglage de luminosite jusqu'a 10 h d'exposition.",
    },
    {
      id: "lamp-upgrade-4",
      name: "Lampe horticole IV",
      type: "lamp",
      level: 4,
      cost: 186,
      tier: "Equipement",
      description: "Etend le reglage de luminosite jusqu'a 12 h d'exposition.",
    },
    {
      id: "lamp-upgrade-5",
      name: "Lampe horticole V",
      type: "lamp",
      level: 5,
      cost: 248,
      tier: "Equipement",
      description: "Etend le reglage de luminosite jusqu'a 14 h d'exposition.",
    },
    {
      id: "co2-upgrade-2",
      name: "Diffuseur CO2 II",
      type: "co2",
      level: 2,
      cost: 82,
      tier: "Equipement",
      description: "Augmente la production maximale automatique de CO2 jusqu'au niveau 6.",
    },
    {
      id: "co2-upgrade-3",
      name: "Diffuseur CO2 III",
      type: "co2",
      level: 3,
      cost: 136,
      tier: "Equipement",
      description: "Augmente la production maximale automatique de CO2 jusqu'au niveau 8.",
    },
    {
      id: "co2-upgrade-4",
      name: "Diffuseur CO2 IV",
      type: "co2",
      level: 4,
      cost: 194,
      tier: "Equipement",
      description: "Augmente la production maximale automatique de CO2 jusqu'au niveau 10.",
    },
    {
      id: "co2-upgrade-5",
      name: "Diffuseur CO2 V",
      type: "co2",
      level: 5,
      cost: 256,
      tier: "Equipement",
      description: "Augmente la production maximale automatique de CO2 jusqu'au niveau 12.",
    },
    {
      id: "filter-upgrade-2",
      name: "Filtre II",
      type: "filter",
      level: 2,
      cost: 70,
      tier: "Equipement",
      description: "Reduit l'impact du cycle sur la qualite de l'eau de 8%.",
    },
    {
      id: "filter-upgrade-3",
      name: "Filtre III",
      type: "filter",
      level: 3,
      cost: 112,
      tier: "Equipement",
      description: "Reduit l'impact du cycle sur la qualite de l'eau de 10%.",
    },
    {
      id: "filter-upgrade-4",
      name: "Filtre IV",
      type: "filter",
      level: 4,
      cost: 164,
      tier: "Equipement",
      description: "Reduit l'impact du cycle sur la qualite de l'eau de 12%.",
    },
    {
      id: "filter-upgrade-5",
      name: "Filtre V",
      type: "filter",
      level: 5,
      cost: 224,
      tier: "Equipement",
      description: "Reduit l'impact du cycle sur la qualite de l'eau de 14%.",
    },
    {
      id: "plant-anubias-nana",
      name: "Anubias nana",
      type: "plant",
      plantType: "anubias-nana",
      cost: 42,
      tier: "Stable",
      description: "Une plante compacte et fiable pour installer un premier massif sans stress.",
    },
    {
      id: "plant-microsorum-java",
      name: "Microsorum",
      type: "plant",
      plantType: "microsorum-java",
      cost: 54,
      tier: "Feuillage",
      description: "Une fougere de Java souple et volumineuse pour densifier le decor plante.",
    },
    {
      id: "plant-cryptocoryne-wendtii",
      name: "Cryptocoryne wendtii",
      type: "plant",
      plantType: "cryptocoryne-wendtii",
      cost: 48,
      tier: "Dense",
      description: "Une plante de milieu de bac tres utile pour meubler les zones calmes.",
    },
    {
      id: "plant-vallisneria-spiralis",
      name: "Vallisneria spiralis",
      type: "plant",
      plantType: "vallisneria-spiralis",
      cost: 62,
      tier: "Oxygenante",
      description: "Une grande plante rubanee qui donne de la hauteur et produit beaucoup d'oxygene.",
    },
    {
      id: "plant-echinodorus-bleheri",
      name: "Echinodorus bleheri",
      type: "plant",
      plantType: "echinodorus-bleheri",
      cost: 68,
      tier: "Maitre",
      description: "Une grande rosette puissante pour structurer durablement le fond du bac.",
    },
  ],
  communityPlayers: [
    {
      id: "naya",
      name: "Naya",
      aquarium: "Atelier des hippocampes",
      specialty: "Elevage zen",
      visitors: 128,
      mood: "Organise des visites guidees pour debutants.",
      gift: "food",
    },
    {
      id: "marin",
      name: "Marin",
      aquarium: "Courant saphir",
      specialty: "Plantes rares",
      visitors: 204,
      mood: "Collectionne des arches minieres et des coraux massifs.",
      gift: "coins",
    },
    {
      id: "thea",
      name: "Thea",
      aquarium: "Lagune de lune",
      specialty: "Poissons rares",
      visitors: 176,
      mood: "Partage souvent des astuces sur les bettas splendens.",
      gift: "pearls",
    },
    {
      id: "sami",
      name: "Sami",
      aquarium: "Jardin abyssal",
      specialty: "Evenements",
      visitors: 149,
      mood: "Lance des mini-defis communautaires chaque semaine.",
      gift: "food",
    },
    {
      id: "eloi",
      name: "Eloi",
      aquarium: "Terrasse aux raies",
      specialty: "Collection tardive",
      visitors: 265,
      mood: "Met en scene les especes legendaires dans de grands bacs thematiques.",
      gift: "pearls",
    },
    {
      id: "mae",
      name: "Mae",
      aquarium: "Studio des lagunes",
      specialty: "Aesthetique",
      visitors: 188,
      mood: "Compose des bacs tres photographiques avec peu d'especes mais beaucoup de style.",
      gift: "coins",
    },
  ],
  events: [
    {
      id: "coral",
      name: "Maree des coraux",
      badge: "Evenement corallien",
      description:
        "Les visiteurs affluent pour admirer les aquariums les plus luxuriants. Les visites rapportent 25% de coquillages en plus.",
      visitBonusMultiplier: 1.25,
    },
    {
      id: "pearls",
      name: "Nuit des perles",
      badge: "Festival des perles",
      description:
        "Les poissons rares brillent davantage. Chaque recompense quotidienne donne des perles supplementaires.",
      dailyPearlsBonus: 6,
    },
    {
      id: "fry",
      name: "Fete des alevins",
      badge: "Saison des naissances",
      description:
        "Les tentatives de reproduction ont plus de succes et les jeunes poissons grandissent plus vite.",
      breedBonus: 0.18,
    },
    {
      id: "royal",
      name: "Salon royal",
      badge: "Semaine prestige",
      description:
        "Les especes epic et legendaires rapportent davantage de reputation et de coquillages.",
      rareIncomeBonus: 1.2,
    },
    {
      id: "flora",
      name: "Expo botanique",
      badge: "Expo botanique",
      description:
        "Les bacs riches en plantes naturelles gagnent plus de joie et de visiteurs pendant la semaine.",
      decorVisitorBonus: 6,
    },
    {
      id: "harbor",
      name: "Port en fete",
      badge: "Port en fete",
      description:
        "Les interactions communautaires sont mieux recompensees et les cadeaux sont plus frequents.",
      socialCoinsBonus: 12,
    },
  ],
  tips: [
    "Des poissons bien nourris et une eau propre augmentent naturellement les visites.",
    "Une belle selection de plantes rend ton aquarium plus memorable et plus vivant.",
    "Les especes rares donnent moins de revenus immediats mais tirent la progression sur la duree.",
    "Visiter souvent le port communautaire est une bonne source de recompenses et d'idees d'amenagement.",
    "Un bac qui raconte une histoire est souvent plus marquant qu'un simple empilement de raretes.",
    "La reproduction devient plus interessante une fois tes adultes bien stabilises.",
    "Les evenements sont parfaits pour faire tourner la meta sans casser l'economie.",
    "Le contenu saisonnier doit idealement recompenser la connexion reguliere sans punir l'absence.",
  ],
  missionPool: [
    {
      id: "feed-2",
      label: "Nourrir tes pensionnaires 2 fois",
      goal: 2,
      rewardCoins: 45,
      rewardPearls: 2,
      tracker: "feedCount",
    },
    {
      id: "feed-4",
      label: "Assurer 4 services de nourriture",
      goal: 4,
      rewardCoins: 82,
      rewardPearls: 4,
      tracker: "feedCount",
    },
    {
      id: "visit-2",
      label: "Visiter 2 aquariums communautaires",
      goal: 2,
      rewardCoins: 38,
      rewardPearls: 3,
      tracker: "visitCount",
    },
    {
      id: "visit-4",
      label: "Faire une tournee de 4 visites",
      goal: 4,
      rewardCoins: 88,
      rewardPearls: 5,
      tracker: "visitCount",
    },
    {
      id: "buy-1",
      label: "Acheter une ressource ou une deco",
      goal: 1,
      rewardCoins: 34,
      rewardPearls: 1,
      tracker: "purchaseCount",
    },
    {
      id: "buy-3",
      label: "Effectuer 3 achats dans la boutique",
      goal: 3,
      rewardCoins: 94,
      rewardPearls: 4,
      tracker: "purchaseCount",
    },
    {
      id: "clean-2",
      label: "Nettoyer l'eau 2 fois",
      goal: 2,
      rewardCoins: 52,
      rewardPearls: 2,
      tracker: "cleanCount",
    },
    {
      id: "oxygen-2",
      label: "Oxygener le bac 2 fois",
      goal: 2,
      rewardCoins: 44,
      rewardPearls: 2,
      tracker: "oxygenCount",
    },
    {
      id: "adopt-1",
      label: "Adopter un nouveau poisson",
      goal: 1,
      rewardCoins: 60,
      rewardPearls: 3,
      tracker: "adoptionCount",
    },
    {
      id: "breed-1",
      label: "Tenter une reproduction",
      goal: 1,
      rewardCoins: 66,
      rewardPearls: 4,
      tracker: "breedCount",
    },
    {
      id: "decor-1",
      label: "Installer une nouvelle deco",
      goal: 1,
      rewardCoins: 58,
      rewardPearls: 2,
      tracker: "decorateCount",
    },
    {
      id: "reward-1",
      label: "Recuperer la recompense du jour",
      goal: 1,
      rewardCoins: 32,
      rewardPearls: 2,
      tracker: "dailyRewardCount",
    },
  ],
  missionTrackers: [
    "feedCount",
    "visitCount",
    "purchaseCount",
    "cleanCount",
    "oxygenCount",
    "adoptionCount",
    "breedCount",
    "decorateCount",
    "dailyRewardCount",
  ],
  fishNames: {
    prefixes: ["Aster", "Nemo", "Kora", "Vega", "Lilo", "Nova", "Rubi", "Siro", "Iris", "Melo"],
    suffixes: ["bleu", "perle", "flot", "mousse", "sel", "corail", "aube", "brume", "ivoire", "lagon"],
    babies: ["Pixel", "Etoile", "Plume", "Bulle", "Luciole", "Mica", "Tide", "Pico", "Nacre", "Miro"],
  },
};
